# Generated by Django 5.2.8 on 2025-12-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='language',
            field=models.CharField(choices=[('pl', 'Polski'), ('en', 'English'), ('de', 'Deutsch')], default='pl', max_length=2),
        ),
    ]
